// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // الـ CLI (migrate/generate) يستخدم DIRECT_URL لو موجود (اتصال مباشر لـ Neon)،
    // وإلا DATABASE_URL. التشغيل نفسه يستخدم DATABASE_URL (pooled) عبر database.service.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
